### PR TITLE
Git all

### PR DESCRIPTION
**Pull request by jeunito**
@jonlives continuing my work in https://github.com/jonlives/knife-spork/pull/173. I moved repositories. My apologies for the delay here. I went on a long vacation and just recently had time. I should be done with this by the end of the week.

### CODE REVIEW

**Comment by jeunito** [comment]
This should be ready now @jonlives

**Comment by jonlives** [comment]
@jeunito brilliant, thanks for this - I'll take a look at the code and get this tested, should hopefully get it out in the next release.

**Comment by jonlives** [comment]
@jeunito hoping to start look at this this week - please could you undo the removal of the .ruby-gemset and .ruby-version files though.

**Comment by jonlives** [comment]
@jeunito could you also please add some example documentation to README.md of using these plugins and then add / modify the relevant files under the plugins folder at repo root to explain the differences between the git and gitall plugins, what each should be used for, what options they support etc?

**Comment by jeunito** [comment]
Acknowledged. Will do this tonight.

On Tue, Jun 30, 2015 at 9:55 AM, Jon Cowie <notifications@github.com> wrote:

> @jeunito <https://github.com/jeunito> could you also please add some
> example documentation to README.md of using these plugins and then add /
> modify the relevant files under the plugins folder at repo root to explain
> the differences between the git and gitall plugins, what each should be
> used for, what options they support etc?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jonlives/knife-spork/pull/187#issuecomment-117255115>.
>



-- 
JOSE ASUNCION

Where I hangout: https://twitter.com/#!/Jeunito
See my byte size recipes: http://jeunito.me

**Comment by jonlives** [comment]
Awesome thanks!

**Comment by jeunito** [comment]
@jonlives  Actually I merged the git_all into the git plugin so that file shouldn't be there anymore. What's left now is just to add the documentation

**Comment by jonlives** [comment]
@jeunito great, thanks! It'll take me a while to get this tested out and so on, but I'm aiming to have it out in the next release if all goes well.

**Comment by jonlives** [comment]
I've just merged this into the release branch (1.6.0) - I've got a couple more minor issues to finish up before release, but this should be going out again this week. Thanks so much again for all of your hard work on this - I actually went back to test this and realised I'd left my beta build installed for weeks and had been using this without noticing so clearly it works pretty well :p

**Pull request merged**
