### PR TITLE
add missing yajl require

### PR DESCRIPTION
**Pull request by oker1**
If there was a problem with the environment file (i.e. missing) you got an error like this instead of the real error:

```uninitialized constant KnifeSpork::Runner::InstanceMethods::Yajl```

### CODE REVIEW

**Comment by jonlives** [comment]
@oker1 and @mrjcleaver, any chance you could take a look at the https://github.com/jonlives/knife-spork/releases/tag/1.5.0.beta1 release which has this fix in it (I modified the PR to use chef's ffi_yajl) and double check it fixes the issues you were seeing?

**Comment by jonlives** [comment]
Actually hold off on this, one more PR to merge to fix this..

**Comment by jonlives** [comment]
@oker1 and @mrjcleaver, any chance you could try out https://github.com/jonlives/knife-spork/releases/tag/1.5.0.beta2 and see if it fixes this issue? The constant name of the class I was rescuing changed in chef-client 12 so I've added an alternate fix for this and want to double check it works for you.

**Comment by mrjcleaver** [comment]
Per https://github.com/jonlives/knife-spork/issues/170#issuecomment-71475086 looks good to me. Thanks, M.

**Comment by oker1** [comment]
Works great:

```
> $ knife spork environment check test
ERROR: knife encountered an unexpected error
This may be a bug in the 'spork environment check' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NameError: uninitialized constant KnifeSpork::Runner::InstanceMethods::Yajl

oker@tzs-mbp15 /tmp                                                                      [13:21:44]
> $ chef gem install ~/Downloads/knife-spork-1.5.0.beta2.gem
WARNING:  You don't have /Users/oker/.chefdk/gem/ruby/2.1.0/bin in your PATH,
	  gem executables will not run.
Successfully installed knife-spork-1.5.0.beta2
1 gem installed

oker@tzs-mbp15 /tmp                                                                      [13:22:08]
> $ knife spork environment check test
ERROR: Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/oker/.chef/environments/test.json
```

**Pull request merged**
